### ISSUE TITLE
On windows, the filepath for loadImage() is broken

### ISSUE THREAD

**Issue by DavideBecker** [pixelkind/dalton#8]
It looks like whatever you're using to resolve the current filepath isn't working on Windows and just results in `undefined`. In the debug console, the image object always points to `<daltonpath>/resources/app/demos/simple/undefined/imagename.png`. If I store images there it loads them correctly, but if I store them in the same location as the .js file it doesn't.

**Comment by pixelkind** [comment]
fixed in 0.4.1
